### ISSUE TITLE
Big circle at the start

### ISSUE THREAD

**Issue by jhoermann** [selemondev/vue3-signature-pad#14]
### Problem
Using mouse will trigger a big circle at the start when "maximum pen line thickness" > "minimum pen line thickness".

![image](https://github.com/user-attachments/assets/00a8742a-aec6-4b1b-8be2-31f01b4e087f)

### Expected behaviour
I would expect that the first mouse contact would blend nicely with the line.

**Comment by selemondev** [comment]
Hey @jhoermann, this issue has been resolved. you can check it out [here](#15).

**Comment by jhoermann** [comment]
Nice @selemondev! Indeed looks better now.
